### ISSUE TITLE
Scripts to reproduce tables from paper

### ISSUE THREAD

**Issue by cthorrez** [dustalov/evalica#23]
Hello! I recently read your paper and I also have an interest in efficient implementations of rating systems. I'm wondering if you can share the scripts available to reproduce table 1 comparing evalica to the ChatBot Arena implementation? I did some work earlier this year upgrading their system from the logistic regression version to a more optimized version and I'm curious to benchmark my version under the same conditions as evalica.

My PR for chatbot arena for reference https://github.com/lm-sys/FastChat/pull/3523

**Comment by dustalov** [comment]
Hi, thank you for your interest in the paper!

Please find the script at https://gist.github.com/dustalov/6c79e4c3e384e069cc8e95cfb37ffc7d. Once you've successfully replicated the experiments, please let me know, so I can upload the script directly to this repository instead of keeping it as a gist. The script produces these results on my machine: [performance_arena.csv](https://github.com/user-attachments/files/18203727/performance_arena.csv).

Important points:

- The Elo implementation was taken from [the official notebook](https://colab.research.google.com/drive/1KdwokPjirkTmpO_P1WByFNFiqxWQquwH) at https://lmarena.ai/
- The Bradley&ndash;Terry implementation was taken from https://github.com/lmarena/arena-hard-auto/blob/2971e34d066f986c09bc5a463fa286fa93bcca3c/utils_math.py#L38-L69
- In my experiments, ties in the dataset were not excluded. However, note that the Chatbot Arena's notebook does exclude ties, resulting in a significant amount of data being omitted from the official comparisons, making them faster.

**Comment by cthorrez** [comment]
Thank you for sharing, I will work to also reproduce and compare with the updated implementation. There are a couple of things to note. One is that the actual ChatBot Arena leaderboard is generated by the code in their fastchat repo (https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/monitor/elo_analysis.py) and the notebook is more for reference and no longer completely up to date. 

In the notebook they do indeed filter the df to exclude ties `battles_no_ties = battles[~battles["winner"].str.contains("tie")]`, but when they fit the Elo and BT models, they actually use the original battles dataframe not the one where the ties have been filtered out. (battles rather than battles_no_ties)
`online_elo_ratings = compute_online_elo(battles)`, `elo_mle_ratings = compute_mle_elo(battles)`

**Comment by dustalov** [comment]
Thanks for explaining the tie-exclusion part—it always confused me.  

By the way, I think the vectorized Elo implementation is really cool. Would you mind if I port it to Evalica?

**Comment by cthorrez** [comment]
Fine by me! just maybe add a link or comment attribution that it is adapted from the FastChat repo

**Comment by cthorrez** [comment]
Hi, I got some time to look into this. I was able to run your script and basically reproduce table 1 += the noise of me running on different hardware. I just have a small clarification question, in table 1 of the paper, the methods are labeled "Elo from Arena-hard" and "BT from Chatbot Arena", but in the code for performance_arena.py it seems more like it's BT from Arena-Hard and Elo from Chatbot Arena. I don't think this really makes a difference since they are by the same people and for the most part copy pastes of each other.

For the second part, I was able to benchmark the new implementations and confirmed that the new BT implementation is much faster than the old one but still slower than evalica. But based on my own experience optimizing the Chatbot Arena implementations, one thing I learned is that the preprocessing I applied is actually a non-trivial amount of the time. So I did a further test and added a `NUMBER` param in addition to the repetitions, and added another candidate which is the accelerated bootstrap BT from Chatbot arena. This one does the preprocessing once and uses the preprocessed data for all bootstrap samples at once and in parallel using multi-processing.

I know this makes it not completely a fair comparison just thought it would be interesting to test as a demonstration that there a lot of different dimensions in which these things can be optimized. Feel free to checkout my fork with a modified `performance_arena.py` and `rating_systems.py` taken from FastChat. https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/monitor/rating_systems.py.

https://github.com/cthorrez/evalica/commit/c7a9d77ead798ea2452c403cd217e16a2ca0aa38

Here are my overall results with both `NUMBER` and `REPETITIONS` set to 10 so it's fitting 100 models per variant:
```
                 algorithm      solver                 time_stats
0  bootstrap bradley_terry  fast arena     5.46927208120178 ± 0.3
1            bradley_terry     evalica     9.60150884159666 ± 0.2
2            bradley_terry  fast arena   34.93809527509147 ± 2.05
3                      elo       arena  26.159585607002374 ± 2.01
4                      elo     evalica  11.867467720393325 ± 0.42
```

Also just for reference if you are interested in my blog post about the optimizations specifically for the bootstrap version.
https://www.claytonthorrez.com/blog/posts/fast_llm_ratings/

**Comment by dustalov** [comment]
Glad to hear that the reproduction was a success! I plan to upload the scripts this weekend.

I double-checked the labels, and there is a typo in Table 1: the third line should be `Elo from Chatbot Arena`, and the fourth line should be `BT from Arena-Hard`. Thank you for catching this; the updated arXiv preprint will include the fix.

When I built Evalica, I wanted it to be flexible and not bound to a specific benchmark, so users could easily build their own leaderboards with it (though, of course, I followed Chatbot Arena and other popular benchmarks). The bootstrapping component of Evalica is still in the early stages, as I focused on the performance of individual implementations.

I used a naïve form of bootstrapping in my experiments, although there may be other optimizations to explore, such as multithreading and reducing computation. I'm still designing a clean API for confidence intervals, but it's a work in progress.

While I agree that sampling from the multinomial distribution of scores should speed up computation, I recommend running comparisons with the naïve approach to study the variance of the item scores, ensuring that no important information is lost.

**Comment by cthorrez** [comment]
That makes sense to me, I may be able to help contribute optimizations as the bootstrapping functionality fills out. Thanks for helping me get up and running to repro the paper and start comparisons. I'll close this issue since my questions are all answered.

**Comment by dustalov** [comment]
Added the code: https://github.com/dustalov/evalica/tree/master/coling2025.
