### ISSUE TITLE
The motivation of using Rust for the implementation?

### ISSUE THREAD

**Issue by shenxiangzhuang** [dustalov/evalica#5]
Hi @dustalov ! I'm wondering why we choose rust here for the implementation of algorithms. IMHO, rust does have much better performance compare to python, is this the main reason of using it or there are other reasons?

**Comment by dustalov** [comment]
Hi @shenxiangzhuang, that's an excellent question!

I have not published the technical vision yet, so let me outline it in this response.

Python has some excellent numerical libraries, like NumPy and all the deep learning toolkits, yet Python itself is a rather slow language. At the same time, Rust is a nice, safe, and relatively fast language with great interoperability capabilities with the major scripting runtimes, including CPython via [PyO3](https://pyo3.rs/), Node.js via [Neon](https://neon-rs.dev/), etc.

I find it useful to have trusted implementations of pairwise comparison methods, which are both fast and correct. Implementing them once in Rust makes all of them fast enough and available for most languages with relatively low effort. I expect to provide the other languages only with the Rust implementations.

```mermaid
flowchart LR
    Python --->|naïve| Rust
    Rust ---> Python
    Rust ---> Node.js
    Rust ---> ...
```

This approach has a small problem. Python is a popular choice for method prototyping, and Rust is likely not. I approached this problem by having two implementations of each algorithm: one is called naïve in Python to ensure numerical correctness and another in Rust, which should be faster and output the same scores for the given inputs as the Python version. This is why Evalica has a very extensive test suite that attempts to ensure the desired correctness.

**Comment by dustalov** [comment]
It is very difficult to outperform NumPy code. However, where raw Python is used, even a straightforward Rust implementation shows impressive results; see https://codspeed.io/dustalov/evalica/runs/66ba73428bb287a9c7d9f484 for example:

- `test_llmfao_performance[elo-naive]`: 2.7 s
- `test_llmfao_performance[elo-pyo3]`: 46.7 ms (50 times faster!)

**Comment by shenxiangzhuang** [comment]
Cool! Thanks for your careful and insightful explanation, which helps a lot. The method, "two implementations of each algorithm", does open my mind and I think it's very elegant way to make the keep the algorithm's correctness and efficiency.

By the way, I use the similar method to test the rust implementation in my tiny project([bleuscore](https://github.com/shenxiangzhuang/bleuscore), rust backend BLEU score calculator with python binding), but I only use the naive python implementation in test for result comparison. And I think the method used in `evalica` is much better, thanks for your work!
